from __future__ import annotations

from collections.abc import Iterator, Sequence
from typing import Any, Protocol

from graphrag.embed.base import Matrix, Vector
from graphrag.models import (
    Chunk,
    Document,
    Enrichment,
    Entity,
    GraphStats,
    PersonaSpec,
    RelatedTopic,
    ScoredChunk,
    SpeakerCount,
    TopicCount,
)


class GraphStore(Protocol):
    """Every operation the pipeline, retriever, CLI and MCP server need from the graph."""

    # schema / lifecycle
    def ensure_schema(self, dim: int) -> None: ...
    def close(self) -> None: ...

    # writes
    def upsert_persona(self, persona: PersonaSpec) -> None: ...
    def upsert_documents(self, documents: Sequence[Document]) -> None: ...
    def upsert_chunks(self, chunks: Sequence[Chunk], embeddings: Matrix) -> None: ...
    def upsert_topic_cooccurrence(self, pairs: Sequence[tuple[str, str, int]]) -> None: ...
    def upsert_enrichment(self, enrichment: Enrichment) -> None: ...
    def delete_persona(self, persona_id: str) -> None: ...
    def delete_documents(self, doc_ids: Sequence[str]) -> None: ...

    # search
    def vector_search(
        self, vector: Vector, k: int, persona_id: str | None = None
    ) -> list[ScoredChunk]: ...
    def fulltext_search(
        self, query: str, k: int, persona_id: str | None = None
    ) -> list[ScoredChunk]: ...

    # reads
    def get_chunks(self, chunk_ids: Sequence[str]) -> list[Chunk]: ...
    def neighbors(self, chunk_id: str, hops: int = 1) -> list[Chunk]: ...
    def get_document(self, doc_id: str) -> Document | None: ...
    def list_documents(
        self,
        persona_id: str | None = None,
        *,
        topic: str | None = None,
        speaker: str | None = None,
        limit: int = 50,
    ) -> list[Document]: ...
    def document_chunks(self, doc_id: str, start: int = 0, count: int = 5) -> list[Chunk]: ...
    def list_topics(self, persona_id: str | None = None, limit: int = 50) -> list[TopicCount]: ...
    def related_topics(
        self, topic: str, persona_id: str | None = None, limit: int = 10
    ) -> list[RelatedTopic]: ...
    def list_speakers(
        self, persona_id: str | None = None, limit: int = 50
    ) -> list[SpeakerCount]: ...
    def list_personas(self) -> list[PersonaSpec]: ...
    def entities_for_chunks(self, chunk_ids: Sequence[str]) -> list[Entity]: ...
    def enriched_doc_ids(self, persona_id: str) -> set[str]: ...

    # bulk (snapshots)
    def iter_documents(self, persona_id: str) -> Iterator[Document]: ...
    def iter_chunks(self, persona_id: str) -> Iterator[tuple[Chunk, Vector]]: ...
    def enrichment_for_persona(self, persona_id: str) -> Enrichment: ...

    # misc
    def stats(self) -> GraphStats: ...
    def run_readonly_cypher(
        self, query: str, params: dict[str, Any] | None = None
    ) -> list[dict[str, Any]]: ...
